[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/data.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Optional: pretty URLs for future routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
